# ? Datenbank-Art definieren (H2)
quarkus.datasource.db-kind=h2
# ? JDBC URL für eine In-Memory-Datenbank (H2)
# DB_CLOSE_DELAY=-1 stellt sicher, dass die DB nicht geschlossen wird, solange die JVM läuft.
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
# ? Standard-Zugangsdaten (optional für H2 In-Memory)
quarkus.datasource.username=sa
quarkus.datasource.password=sa
# ? Schema-Generierung: Erstellt die Tabellen basierend auf Ihren Entities beim Start neu
quarkus.hibernate-orm.database.generation=drop-and-create
# ? Optional: Zeigt die generierten SQL-Anweisungen in der Konsole an
quarkus.hibernate-orm.log.sql=true
# ?? Optional: Aktiviert die H2-Webkonsole (praktisch zum Prüfen der Daten)
quarkus.h2-console.enabled=true
quarkus.h2-console.path=/h2-console
quarkus.http.port=8085
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://org.backwarden.api
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.sign=true
# Activate JWT
quarkus.http.auth.proactive=true
quarkus.http.auth.permission.public.paths=/users,/token,/api
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated

quarkus.container-image.group=org.backwarden
quarkus.container-image.name=api
quarkus.container-image.tag=1.0.0
